<?php
  require "template.php";
  headers("Fale's TS - About Me");
?>
<h1>About Me</h1><br/>
<p>I'm Fabio Alessandro Locati, usully known in the world wilde web as Fale or F4l3. I'm an eighteen years old italian guy. I'm studing at the Tecnological Liceo Scientifico, at J.C.Maxwell school, in Milan. I have studied my 12th year (2007/2008) in California, thanks to the Rotary's Youth Exchange Program. I stareted programming in my 6th grade and I have never stopped because I truly love it. I have started with BASIC, and after I have learned Gw Basic, Quick Basic, Visual Basic, and php during my three years of middle school. During my High School years I have studied several languages but, mainly, I have discovered the C/C++ languages and I felt in love with that. After some years of little programs written in C/C++ in January 2008 I choosed to joined the KDE devel team, and I helped the multimedia program: DragonPlayer. In March of the same year I said myself: "why the bots for wikipedia are all written with interpretated languages? Why not write a C++ bot?". I looked around the web and I have discovered that tere is no 100% automatic bot that runs on a wiki-service and is written in C++. I start writing a framework (wiki++) that is now available from this web site under the terms of the GPLv3. At that point I have written some wiki bots in C++ using my framework. I'm developping as fast as I can the framework and I have the goal of releasing the version 1.0 for the end of the year (2008). I think write bots in C++ is way better for a lot of reasons. The most important, from my point of view, is the velocity and the lightness of the programs in C++ (the bots that I run on the toolserver result to use less than the 1% of a single CPU and 0Mb of RAM). The downside is that you have to recompile every time you change machine. I'm trying to resolve this problem creating some scripts that you only have to run to compile a bot.</p>
<?php
  footer();
?>
